### PR TITLE
player respond should go correct method

### PR DESCRIPTION
**Pull request by HFAsif**
so i used a try catch to go second method ,

### CODE REVIEW

**Comment by developerss** [comment]
wait it works one time but second time not works to download , without try ,

**Comment by developerss** [comment]
Newtonsoft.Json.Linq.JObject.Parse(extractedJson)["args"]["player_response"].ToString(); here the exception occured

**Comment by developerss** [comment]
error came to this line

**Comment by HFAsif** [comment]
i have changed this (@"""jsUrl""\s*:\s*""([^""]+)"""); buy following your fix 
and JObject.Parse also changed by following but still same any video cant load exception at same please , but try catch only works to skip this stepp
i really want ur suggession and fix

**Comment by LinPolly** [comment]
I refer to the content of youtube-dl, but I cannot search for ytplayer.config.
In fact, the ytplayer.config js syntax is the same as the next Regex answer after execution, so delete the Regex of ytplayer.config.

**Comment by HFAsif** [comment]
delete dataRegex = new Regex(@"ytplayer\.config\s*=\s*(\{.+?\});", RegexOptions.Multiline);? ?

**Comment by HFAsif** [comment]
ahh you mean remove this code , yes it works without this code 
"
//if (dataMatch.Success)
            //{
            //    string extractedJson = dataMatch.Result("$1");
            //    if (!extractedJson.Contains("raw_player_response:ytInitialPlayerResponse")) //https://www.youtube.com/watch?v=9Y7TRMISkGE
            //        {
            //            player_response = Newtonsoft.Json.Linq.JObject.Parse(extractedJson)["args"]["player_response"].ToString();
            //            return YoutubeModel.FromJson(player_response);
            //        }

                    
            //    }
            //}
"

??

yes remove this code now works , but i think if yt some video use this resonce to see video , 
thank you

**Pull request merged**
