### PR TITLE
in line 88 getting exception

### PR DESCRIPTION
**Pull request by HFAsif**
hi lin polly , i am getting exception at line number 88 , i think youtube changes their signeture , can you please look at it ,

### CODE REVIEW

**Comment by HFAsif** [comment]
its great works now but there is another problem in line 285 LoadModel => "player_response"
, this could be happen when i download sign video , can you please look at it

**Comment by developerss** [comment]
can you please check this link to download https://www.youtube.com/watch?v=WNeLUngb-Xg 
getting exception in player_response , line 285 .

**Comment by HFAsif** [comment]
this problem in some of sig video but some of sig video works to download , i think the error in parsing jason , 
example link = https://www.youtube.com/watch?v=eVTXPUF4Oz4  ,   https://www.youtube.com/watch?v=WNeLUngb-Xg
both of this same problem

**Comment by LinPolly** [comment]
Fix at [70b87a8](https://github.com/LinPolly/YoutubeExtractor/commit/d1c78d6295fec728667c44e417ff9032c7ec4cd2)
Thanks for filing the bug

**Comment by HFAsif** [comment]
thank you too , awesome fixed

**Pull request closed without merging**
